services:
  postgres:
    image: postgres:15-alpine
    container_name: quiz-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - quiz-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  quiz-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quiz-server-app
    restart: unless-stopped
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}
      HIBERNATE_DDL_AUTO: ${HIBERNATE_DDL_AUTO}
      SHOW_SQL: ${SHOW_SQL}
      FORMAT_SQL: ${FORMAT_SQL}
      FLYWAY_ENABLED: ${FLYWAY_ENABLED}
    ports:
      - "${SERVER_PORT}:8081"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - quiz-network

volumes:
  postgres_data:
    driver: local

networks:
  quiz-network:
    driver: bridge