server:
  port: ${SERVER_PORT}

logging:
  level:
    org:
      springframework:
        security: ERROR

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-expiration-in-ms: ${JWT_ACCESS_EXPIRATION:3600000}
  refresh-expiration-in-ms: ${JWT_REFRESH_EXPIRATION:604800000}

spring:
  application:
    name: quiz-server
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/db_quiz_server}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:validate}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:true}
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    locations: classpath:db/migration
